name: PEWO_new
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - rappas
  - epa-ng
  - pplacer
  - appspam
  - dendropy
  - biopython=1.76
  - ete3
  - hmmer=3.3
  - numpy=1.18.1
  - openjdk=11.0.1
  - paml=4.9
  - pandas=1.0.1
  - phyml=3.3.20190909
  - pip=20.0.2
  - python=3.6.7
  - pyyaml=5.3
  - r-base=3.6.1
  - r-cairo=1.5_10
  - r-ggplot2=3.2.1
  - r-rcolorbrewer=1.1_2
  - r-reshape2=1.4.3
  - r-stringi=1.4.6
  - r-stringr=1.4.0
  - raxml=8.2.12
  - raxml-ng=0.9.0
  - snakemake
  - sqlalchemy=1.3.13
  - sqlite=3.30.1
  - taxtastic=0.8.11
  - xlrd=1.2.0
  - yaml=0.2.2
  - pip:
    - apples
    - psycopg2-binary==2.8.4
    - treeswift==1.1.5
    - fastalite==0.3
